### ISSUE TITLE
Fix script usages

### ISSUE THREAD

**Issue by ismcagdas** [aspnetboilerplate/module-zero-template#100]
Both in Mpa and Spa there are lib & Scripts folders but some of them are not used.

**Comment by gpcaretti** [comment]
I reviewed the Mpa project.
It requires only a minimum fix in _Layout.cshtml for using all js libraries from the `.\lib` folder.
With this fix you can completely remove the duplicated folders:
* `.\Abp` folder
* `.\Scripts` folder.

It will follow the same fix for the Angular project, soon.

[_Layout.MPA.zip](https://github.com/aspnetboilerplate/module-zero-template/files/1632420/_Layout.MPA.zip)

**Comment by ismcagdas** [comment]
Thanks @gpcaretti we will check it.

**Comment by gpcaretti** [comment]
As promised, PFA the fix for the MVC5/Angular spa application.
It has been a bit more complicated then the MPA project as it required changes in 3 files:

1. `_Layout.cshtml`
2. `layout.cshtml`
3. `BundleConfig.cs`

With this fix you can completely remove the `.\Abp` folder and *almost* remove the `.\Scripts` folder with the exception of these files, as you don't have them in the `.\lib` directory:

1 `~/Scripts/others/html5shiv.js`
2 `~/Scripts/others/respond.min.js`
3 `~/Scripts/modernizr-2.8.3.js`
4 `~/Scripts/jquery-ui-1.12.1.min.js`
5 `~/Scripts/angular.min.js`
6 `~/Scripts/angular-animate.min.js`
7 `~/Scripts/angular-sanitize.min.js`
8 `~/Scripts/angular-ui-router.min.js`
9 `~/Scripts/angular-ui/ui-bootstrap.min.js`
10 `~/Scripts/angular-ui/ui-bootstrap-tpls.min.js`
11 `~/Scripts/angular-ui/ui-utils.min.js`
12 `~/Scripts/jquery.signalR-2.2.2.min.js`

### Further tasks in case you want to completely remove the  `.\Scripts` folder
- [1] Add a copy of the js files above into the  `.\lib` directory
- [2] Fix  `_Layout.cshtml `:
     * `~/Scripts/others/html5shiv.js`
     * `~/Scripts/others/respond.min.js`
     * `~/Scripts/modernizr-2.8.3.js`
     * `~/Scripts/jquery-ui-1.12.1.min.js`
- [3] Fix  `layout.cshtml `:
     * `~/Scripts/others/html5shiv.js`
     * `~/Scripts/others/respond.min.js`
- [4] Fix  `BundleConfig.cs`:
    * `~/Scripts/angular.min.js`
    * `~/Scripts/angular-animate.min.js`
    * `~/Scripts/angular-sanitize.min.js`
    * `~/Scripts/angular-ui-router.min.js`
    * `~/Scripts/angular-ui/ui-bootstrap.min.js`
    * `~/Scripts/angular-ui/ui-bootstrap-tpls.min.js`
    * `~/Scripts/angular-ui/ui-utils.min.js`
    * `~/Scripts/jquery.signalR-2.2.2.min.js`

Once you will implement these last changes in `.\lib`, you can safety delete `.\Scripts` .

[Layouts.SPA.zip](https://github.com/aspnetboilerplate/module-zero-template/files/1634418/Layouts.SPA.zip)

**Comment by ismcagdas** [comment]
@gpcaretti we have worked on both projects but it seems like it is not possible to remove Script folders. SignalR nuget packages install some scripts under Scripts folder, so I changed usage of signalr from lib folder to Scripts folder.

I'm not sure if this issue is %100 solved with this PR https://github.com/aspnetboilerplate/module-zero-template/pull/120. Please reopen another issue if you find any problems.
