### ISSUE TITLE
deploy application problem

### ISSUE THREAD

**Issue by rqx110** [aspnetboilerplate/module-zero-template#22]
I want to deploy my application base abp framework. I just publish the assembly and files to a folder use visual studio  "web publish", and then copy these files to IIS root folder, create IIS web site, modify web.config connection string to my sql server. When I browser the web site, application didn't ceate the database automatic.
My question is how to deploy it to create database and seed data automatic?

Sorry for my bad english!    :)

**Comment by hikalkan** [comment]
Hi,

I always do it manual. I do it because applying migrations may get much time and first HTTP request waits too much (maybe timeouts). I do it with Migrate.exe of EntityFramework.

You can get info on Migrate.exe on the web. Also, you can find info about auto-run migration with EF.

This is my migrate.exe command to run migrations:

migrate.exe MyProject.EntityFramework.dll /connectionString:"Server=localhost;Database=MyProjectDb;Trusted_Connection=True;" /connectionProviderName:"System.Data.SqlClient"

Copy all files in Tools folder of EF package, copy also your project dlls (for example, all files in web\bin folder). then run such a command.

**Comment by rqx110** [comment]
I've done exactly as you do here. Thank you very much!
