### ISSUE TITLE
About  JS Bug for Presentation layer

### ISSUE THREAD

**Issue by yuanjingxp** [aspnetboilerplate/module-zero-template#6]
runing Module-Zero ,  after the logined ,  successed redirect the home page.

login result code details:
+ data: Object
 - error: null
 - result: null
 - success: true
 -targetUrl: "/"

about code details:
- file "abp.jquery.js" , line 99 , "if (data.success === true) "
![qq 20150801234852](https://cloud.githubusercontent.com/assets/13447106/9022436/f4375ba2-38a7-11e5-85ee-ea10c7a5d675.png)

success values is true , this OK!

![qq 20150801234452](https://cloud.githubusercontent.com/assets/13447106/9022421/655b5492-38a7-11e5-984a-953f4d643a22.png)

but use Module-Zero for other project 
the code is bug, very amazing.

login result code details: (this OK!)
+ data: Object
 - error: null
 - result: null
 - success: true
 -targetUrl: "/"

![qq 20150801234420](https://cloud.githubusercontent.com/assets/13447106/9022426/a1b759ae-38a7-11e5-9800-1baae392b9c3.png)

success values is undefined , no good!
Succes values is true, what's going on ?
can't redirect the home page, is blocking. who tell me?

![image](https://cloud.githubusercontent.com/assets/13447106/9022443/246c3158-38a8-11e5-85d0-0c7ddeec9267.png)

**Comment by hikalkan** [comment]
There is a problem with converting json t camelCase. It seems it serialized as PascalCase. Do you have any configuration for that?

It's defined here: https://github.com/aspnetboilerplate/aspnetboilerplate/blob/master/src/Abp.Web.Api/WebApi/AbpWebApiModule.cs#L81

Maybe you don't use WebApi. This may be problem. I created an issue to move this configuration to .Web instead of .Web.Api. But this maynot be related to your case.

**Comment by hikalkan** [comment]
I found that this is not valid now. Closing it.
