### ISSUE TITLE
DefaultLanguagesCreator creates duplicate languages in single-tenant environment

### ISSUE THREAD

**Issue by matthiaswelz** [aspnetboilerplate/module-zero-template#92]
Not an expert on ABP, but I think I have discovered the reason why I keep getting duplicate languages in a new project created using the template. Not sure if it also has implications in multi-tenancy environments.

The way DefaultLanguagesCreator is implemented it uses the following query to detect whether a language already exists or not (in the template the languages use `null` as `TenantId`):

````C#
if (_context.Languages.Any(l => l.TenantId == language.TenantId && l.Name == language.Name))
````

However, `_context.Languages` gets pre-filtered using the `AbpDataFilters.MayHaveTenant` filter whose `AbpDataFilters.Parameters.TenantId` value defaults to `AbpSession.TenantId`. In a single tenant environment, however, `AbpSession.TenantId` is always 1 (as seen in `ClaimsAbpSession.TenantId`):

````C#
if (!MultiTenancy.IsEnabled)
{
   return MultiTenancyConsts.DefaultTenantId;
}
````

Thus, in a single-tenant environment, `_context.Languages` will always be empty if only languages relevant for the host tenant exist.

I am not exactly sure where this is best fixed, but my guess is that either, DefaultLanguagesCreator should be modified to ignore the `AbpDataFilters.MayHaveTenant` filter completely or `AbpDbContext` should be changed so that the filter defaults to "host tenant or default tenant" (i.e. 1 or null) instead of "default tenant" (i.e. 1):

```
if (!MultiTenancy.IsEnabled)
modelBuilder.Filter(AbpDataFilters.MayHaveTenant, (IMayHaveTenant t, int? tenantId) => t.TenantId == 1 || t.TenantId == null), 0);
```

**Comment by hikalkan** [comment]
Doesn't ``_context.DisableAllFilters()`` work?

**Comment by matthiaswelz** [comment]
Thanks for the reply!

As a workaround, I disabled the `MayHaveTenantFilter` and `MustHaveTenantFilter` globally (as I am in a single-tenant environment). So far, this seems to work. So the `DisableAllFilters` should probably work, too.

However, I am not sure whether this is a "bad practice". Are there any cases where their are needed in a single-tenant environment?  
If not I am wondering whether ABP should do this automatically by default, i.e. let the repository check whether multi-tenancy is enabled and only then set-up the filters?

**Comment by hikalkan** [comment]
Hi,

In the database seed method, we always use ``DisableAllFilters()`` since we want to directly work with the database data without a filter.

Tenancy filters can be disabled globally when your application is single tenant. I also think this is the true approach. In that case, we should ensure that database have not host-specific entities (where tenantid is null) or other tenant entities (tenantid != 1). Module-zero default seed data includes two users: host admin and tenant admin (and corresponding roles) and user name should be unique. If you disable IMayHaveTenant filter in the runtime, you may get errors because there will be 2 users with same username. That's why you should delete host entities.
We haven't disabled it since we sometimes switching between multitenancy and singletenancy and don't want to remove data from database.
BTW, you can disable filters in PreInitialize method of your module:

````C#
            Configuration.UnitOfWork.OverrideFilter(AbpDataFilters.MustHaveTenant, false);
            Configuration.UnitOfWork.OverrideFilter(AbpDataFilters.MayHaveTenant, false);
````

**Comment by matthiaswelz** [comment]
Thanks for the detailed response! I suggest extending the documentation to clarify this: https://github.com/aspnetboilerplate/aspnetboilerplate/pull/2243

**Comment by hikalkan** [comment]
Thank you. Will review the doc change.
